DROP TABLE PRODUCTO;
DROP TABLE ENTREGA;
DROP TABLE NOTICIA;
DROP TABLE FAQ;
DROP TABLE REGALO;
DROP TABLE CATEGORIA;
DROP TABLE USUARIO;

CREATE TABLE USUARIO(
    IDUSU INTEGER, --AUTO_INCREMENT,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(90) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(12),
    EMAIL VARCHAR(50) NOT NULL,
    EPOINT INTEGER DEFAULT 0,
    ADM BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_USU PRIMARY KEY(IDUSU)
);

CREATE TABLE CATEGORIA(
    IDCAT INTEGER, --AUTO_INCREMENT,
    NOMBRE VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPCION VARCHAR(140),
    EPASOC INTEGER NOT NULL, --PUNTOS ASOCIADOS A LA CATEGORIA
    CONSTRAINT PK_CAT PRIMARY KEY(IDCAT)
);

CREATE TABLE REGALO(
    IDREG INTEGER, --AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50),
    EPOINTS INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    --FICHERO DE IMAGEN
    CONSTRAINT PK_REG PRIMARY KEY(IDREG)
    
);

CREATE TABLE FAQ(
    IDFAQ INTEGER, --AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    CONTENIDO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FAQ PRIMARY KEY(IDFAQ)
);

CREATE TABLE NOTICIA(
    IDNOTICIA INTEGER, --AUTO_INCREMENT,
    --FECHA_ALTA TIMESTAMP NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CONTENIDO VARCHAR(500) NOT NULL,
    CONSTRAINT PK_NOT PRIMARY KEY(IDNOTICIA)
);

CREATE TABLE ENTREGA(
    IDENTREGA INTEGER, --AUTO_INCREMENT,
    FECHA_ALTA TIMESTAMP NOT NULL,
    IDUSU INTEGER,
    CONSTRAINT PK_ENT PRIMARY KEY(IDENTREGA),
    CONSTRAINT FK_ENT FOREIGN KEY(IDUSU) REFERENCES USUARIO(IDUSU)
);

CREATE TABLE PRODUCTO(
    IDPROD INTEGER, --AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(50),
    CANTIDAD INTEGER NOT NULL,
    IDCAT INTEGER NOT NULL,
    IDENTREGA INTEGER NOT NULL,
    --FICHERO DE IMAGEN
    CONSTRAINT PK_PROD PRIMARY KEY(IDPROD),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY(IDCAT) REFERENCES CATEGORIA(IDCAT),
    CONSTRAINT FK_PROD_ENT FOREIGN KEY(IDENTREGA) REFERENCES ENTREGA(IDENTREGA)

);
